model:
  swinir:
    target: diffbir.model.swinir.SwinIR
    params:
      img_size: 64
      patch_size: 1
      in_chans: 3
      embed_dim: 180
      depths: [6, 6, 6, 6, 6, 6, 6, 6]
      num_heads: [6, 6, 6, 6, 6, 6, 6, 6]
      window_size: 8
      mlp_ratio: 2
      sf: 8
      img_range: 1.0
      upsampler: "nearest+conv"
      resi_connection: "1conv"
      unshuffle: True
      unshuffle_scale: 8

dataset:
  train:
    target: diffbir.dataset.codeformer.CodeformerDataset
    params:
      # training file list path
      file_list: /root/autodl-tmp/code/DiffBIR/train_ffhq.txt
      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: center
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [8, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 50]
  val:
    target: diffbir.dataset.codeformer.CodeformerDataset
    params:
      # validation file list path
      file_list: /root/autodl-tmp/code/DiffBIR/val_ffhq.txt
      file_backend_cfg:
        target: diffbir.dataset.file_backend.HardDiskBackend
      out_size: 512
      crop_type: center
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso']
      kernel_prob: [0.5, 0.5]
      blur_sigma: [7, 12]
      downsample_range: [1, 12]
      noise_range: [0, 15]
      jpeg_range: [30, 100]

batch_transform:
  target: diffbir.dataset.batch_transform.IdentityBatchTransform

train:
  # experiment directory path
  exp_dir: /root/autodl-tmp/code/DiffBIR/exp/train_stage1_degrad1
  learning_rate: 1e-4
  # total batch size
  batch_size: 12
  num_workers: 16
  train_steps: 30000
  log_every: 100
  ckpt_every: 1000
  image_every: 1000
  val_every: 1000
  resume: /root/autodl-tmp/code/DiffBIR/weights/face_swinir_v1.ckpt
