diffbir:
  task: face
  upscale: 1
  version: v2
  sampler: spaced
  steps: 50
  captioner: none
  pos_prompt: ''
  neg_prompt: 'low quality, blurry, low-resolution, noisy, unsharp, weird textures, out of focus'
  cfg_scale: 4.0
  input: ~
  output: ~
  device: cuda
  precision: fp32
  # default parameters
  start_point_type: noise
  batch_size: 1
  strength: 1
  cleaner_tiled: false
  cleaner_tile_size: 512
  cleaner_tile_stride: 256
  vae_encoder_tiled: false
  vae_encoder_tile_size: 256
  vae_decoder_tiled: false
  vae_decoder_tile_size: 256
  cldm_tiled: false
  cldm_tile_size: 512
  cldm_tile_stride: 256
  rescale_cfg: false
  noise_aug: 0
  s_churn: 0
  s_tmin: 0
  s_tmax: 300
  s_noise: 1
  eta: 1
  order: 1
  guidance: false
  n_samples: 1
  llava_bit: 4
  seed: 231



pisa:
  pretrained_model_path: stabilityai/stable-diffusion-2-1-base
  pretrained_path: pisa_sr.pkl
  seed: 42
  process_size: 512
  upscale: 1
  align_method: adain
  lambda_pix: 1
  lambda_sem: 1
  vae_decoder_tiled_size: 224
  vae_encoder_tiled_size: 1024
  latent_tiled_size: 96
  latent_tiled_overlap: 32
  mixed_precision: fp16
  default: true

gfpgan:
  version: '1.3'
  upscale: 1
  bg_upsampler: realesrgan
  bg_tile: 400
  suffix: ~
  only_center_face: false
  aligned: true
  ext: auto
  weight: 0.5
  # custom settings
  metrics: [clipiqa, musiq]
  cleaner_thresholds: [0.3, 17]
  # metrics: ~
  # cleaner_thresholds: ~

ffanet:
  gps: 3
  blocks: 19
  model_path: ots_train_ffa_3_19.pk

# ftn: ~

# enhance: ~

ftn:
  input_nc: 3
  output_nc: 3
  num_downs: 8
  ngf: 64
  model_path: ftn.pth

enhance:
  enhancer1: [0, 50, 1.1] # for gfpgan else pipeline
  enhancer2: [0, 50, 1.1] # for stage3 pre-process